baseURL = "https://donghyunkim.netlify.app"
languageCode = "en-us"
title = "Dong Hyun KIM"
theme = "cactus"
copyright = "D.H.KIM" # cactus will use title if copyright is not set
disqusShortname = "example" # Used when comments is enabled. Cactus will use site title if not set
# googleAnalytics = "UA-1234-5"


# summaryLength = 2

# Main menu which appears below site header.
[[menu.main]]
name = "Home"
url = "/"
weight = 1

[[menu.main]]
name = "Blog"
url = "/posts"
weight = 2

[[menu.main]]
name = "Tags"
url = "/tags"
weight = 3

[[menu.main]]
name = "About"
url = "/about"
weight = 4

[[menu.main]]
name = "Publications"
url = "/publications"
weight = 5

[markup]
  [markup.tableOfContents]
    endLevel = 4
    ordered = false
    startLevel = 2
  [markup.highlight]
    codeFences = true
    guessSyntax = false
    hl_Lines = ""
    lineNoStart = 1
    lineNos = true
    lineNumbersInTable = false
    noClasses = true
    style = "dracula"
    tabWidth = 4

[params]

  colortheme = "dark" # dark, light, white, or classic
  rss = true # generate rss feed. default value is false
  googleAnalyticsAsync = true # use asynchronous tracking. Synchronous tracking by default
  showAllPostsArchive = false # default
  noindexArchive = true # default, set to true if you don't want search engines to index archive pages (should improve SEO)

  # Home page settings
  description = "Hello, I am Dong Hyun Kim, a researcher in building science, based in Lausanne. You can know more about me on this [about](/about) and my [publication](/publications) section. This blog is an open notebook explorinng my thoughts on (day)lighting research."
  mainSection = "posts" # your main section
  mainSectionTitle = "Blog"
  showAllPostsOnHomePage = false # default
  tocInline = true
  postsOnHomePage = 5 # this option will be ignored if showAllPostsOnHomePage is set to true
  tagsOverview = true # show tags overview by default.
  showProjectsList = false # show projects list by default (if projects data file exists).
  projectsUrl = "https://github.com/gohugoio" # title link for projects list

  # https://gohugo.io/functions/format/#hugo-date-and-time-templating-reference
  dateFormat = "2006-01-02" # default

  # Post page settings
  show_updated = true # default
  showReadTime = false # default

  [params.comments]
    enabled = false # default
    engine = "disqus" # more supported engines will be added.

  # the value of name should be an valid font awesome icon name (brands type)
  # https://fontawesome.com/icons?d=gallery&s=brands
  [[params.social]]
    name = "fa-brands fa-orcid"
    link = "https://orcid.org/0000-0001-9598-2219"
  [[params.social]]
    name = "linkedin"
    link = "https://www.linkedin.com/in/dong-hyun-kim-bba19657/?originalSubdomain=ch"
  [[params.social]]
    name = "email"
    link = "light.donghyunkim@gmail.com"  # no need for "mailto:" in the head